### ISSUE TITLE
Bug de déconnexion

### ISSUE THREAD

**Issue by ClaireVersiniTTP** [data-players/essai-possible#121]
Lorsque je me déconnecte : 
- temps de latence très long
- impossible de m'inscrire avec un autre compte, le bouton switche entre "se connecter/s'enregistrer"
- si je clique pour me loguer avec les communs, ça me ramène sur le compte initial

Vidéo :

**Comment by simonLouvet** [comment]
Bug traité : ecran de loading resté bloqué
