### ISSUE TITLE
A DISSOCIER : ajouter un lien vers l'explication du projet

### ISSUE THREAD

**Issue by simonLouvet** [data-players/essai-possible#16]

**Comment by ClaireVersiniTTP** [comment]
Document de propositions pour les textes et liens explicatifs : https://docs.google.com/presentation/d/1lDS8Lj0cfwSl7Gxk0VhvYQJzX0Lwl1S26BgV_icUU2Q/edit?usp=sharing

**Comment by JulesLecuir** [comment]
done
