### ISSUE TITLE
facilitation du rendez-vous avec texte d'explication

### ISSUE THREAD

**Issue by simonLouvet** [data-players/essai-possible#6]
ajouter un texte pour expliquer que ce sont des rdv ouverts à tous sans prérequis + lien vers explications

**Comment by JulesLecuir** [comment]
Besoin de l'aide du client pour définir le texte voulu

**Comment by simonLouvet** [comment]
“En cliquant sur “prendre une RDV”, vous pourrez choisir un créneau au cours duquel échanger avec l’entreprise pour pouvoir tester un métier. Un mail vous sera envoyé avec les modalités de cette rencontre”

**Comment by ClaireVersiniTTP** [comment]
Choisissez un créneau pour échanger avec l'entreprise

**Comment by JulesLecuir** [comment]
La phrase est changée, je ferme
