### ISSUE TITLE
Back office - création de secteurs, objectifs et savoir-êtres

### ISSUE THREAD

**Issue by ClaireVersiniTTP** [data-players/essai-possible#74]
Lorsqu'on crée un secteur, objectif, ou savoir-être on reste sur la page de création d'objectif qui se vide, sans savoir si l'objectif apparaît bien dans la vue liste ni s'il est possible de continuer de créer d'autres objectifs sans repasser par la vue liste
- soit ramener à la vue liste
- soit mettre un helper indiquant "créer un nouvel objectif"

**Comment by ClaireVersiniTTP** [comment]
UPDATE : il faut cliquer deux fois sur enregistrer pour que l'élément s'enregistre et revenir à la vue liste

**Comment by simonLouvet** [comment]
ergonomie par defaut dubackoffice
