### ISSUE TITLE
Acces à la vue détail de l'offre

### ISSUE THREAD

**Issue by ClaireVersiniTTP** [data-players/essai-possible#82]
Lorsqu'on est sur la vue liste des offres, il n'est pas très intuitif de comprendre qu'en cliquant dessus une vue détaillée va s'ouvrir --> possible soit de mieux mettre en avant que la ligne est cliquable par le design, soit d'ajouter un bouton 'consulter l'offre' ?

**Comment by simonLouvet** [comment]
l'ergonomie existante suffit (arbitrage @ClaireVersiniTTP )
